In [3]:
import pandas as pd

In [15]:
df = pd.read_csv('data/idf.csv')

In [17]:
df.head(50)

,Name,Code,Question,Reponse,nombreconnexion,datepremiereconnexion,datederniereconnexion,echecconnexion,perfenregistre,nombredeprediction,messageenvoye,messagesansreponse
0,Benoitgofadmin,Benoitgofadmin433,Dans quelle ville as-tu couru ta première cour...,martique,5,2025-11-07 09:40:18,2025-11-27 09:21:23,5.0,4.0,0.0,0.0,0.0
1,gofro,gofro8082,Quel est le nom de ton club de course ?,castanet,2,2025-11-25 10:05:45,2025-11-25 11:04:46,1.0,0.0,0.0,0.0,0.0
2,marcantoine,marcantoine7264,Quel est le prénom de ton premier coach ?,cesar,2,2025-11-25 11:01:10,2025-11-25 11:01:42,2.0,0.0,0.0,0.0,0.0
3,fdfdfdf,fdfdfdf8089,Quel est le prénom de ton premier coach ?,gofro,1,2025-11-25 13:41:40,2025-11-25 13:41:40,0.0,2.0,2.0,0.0,0.0
4,gigea,gigea9232,Quel est le prénom de ton premier coach ?,gofro,1,2025-11-25 13:45:58,2025-11-25 13:45:58,0.0,2.0,1.0,0.0,0.0
5,gadfi,gadfi4727,Quel est le prénom de ton premier coach ?,gofro,1,2025-11-25 13:50:35,2025-11-25 13:50:35,0.0,2.0,2.0,0.0,0.0
6,martine,martine5308,Quel est le prénom de ton premier coach ?,gofro,1,2025-11-25 14:09:14,2025-11-25 14:09:14,0.0,2.0,1.0,0.0,0.0
7,martinenela,martinenela3806,Quel est le prénom de ton premier coach ?,dddd,1,2025-11-25 14:10:34,2025-11-25 14:10:34,0.0,2.0,1.0,0.0,0.0
8,kikl,kikl8935,Quel est le prénom de ton premier coach ?,yyy,1,2025-11-25 14:17:31,2025-11-25 14:17:31,0.0,2.0,0.0,0.0,0.0
9,aaa,aaa904,Quel est le prénom de ton premier coach ?,fifi,1,2025-11-25 14:29:19,2025-11-25 14:29:19,0.0,2.0,1.0,0.0,0.0
10,chichi,chichi873,Quel est le prénom de ton premier coach ?,chlag,1,2025-11-27 09:11:55,2025-11-27 09:11:55,0.0,0.0,0.0,0.0,0.0
11,xi,xi8338,Quel est le prénom de ton premier coach ?,gofro7367,1,2025-11-27 09:13:40,2025-11-27 09:13:40,0.0,0.0,0.0,3.0,0.0
12,ws,ws6193,Quel est le prénom de ton premier coach ?,bestman,1,2025-11-27 09:13:57,2025-11-27 09:13:57,0.0,0.0,0.0,0.0,0.0

In [19]:
mdf = pd.read_csv('data/mdf.csv')

In [21]:
mdf.head()

  athlete     message                reponse                     date
0      xi  youpiyoupi     oui trop fun merci  <class 'datetime.date'>
1      xi      encore  c vraimet fuinny baby  <class 'datetime.date'>